### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ghost** [codenamesen/prj-rev-bwfs-tea-cozy#4]
Grade: Exceeds Expectations

Great job with the layout and design of the website! Your code is also well-written and clean and I am glad you added alt attributes to the img elements. 
For improvement, you can add more comments to the code. You can also make the text in the nav bar a lighter color, like white, to make it more easy to see.

As a further challenge, consider adding more pages to the website and creating a drop down menu. This will take some additional research, but I think it will be a neat challenge to work on! Based on your work here, I think you are ready for it!

**Comment by codenamesen** [comment]
Thank You
